name: Build x86
permissions:
  actions: none
  checks: none
  contents: none
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none
      
on:
  workflow_dispatch:

jobs:
  check_images:
    #runs-on: self-hosted
    runs-on: ubuntu-latest
      
    steps:
      - name: Reclaiming disk space on / by removing dotnet/android/ghc
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo apt-get remove google-cloud-sdk azure-cli ghc-9.0.1 ghc-8.10.4 hhvm google-chrome-stable firefox mysql-server-core-8.0 moby-engine mono-devel mongodb-org-server podman moby-cli moby-containerd mongodb-org-mongos powershell dotnet-runtime-3.1 dotnet-runtime-5.0 dotnet-sdk-3.1 dotnet-sdk-5.0
          sudo apt-get autoremove
          
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: bromite
          fetch-depth: 1

      - name: Get current chromium version
        shell: bash
        run: |
          export VERSION=$( cat ./bromite/build/RELEASE )
          echo Current version is $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Check build deps image
        uses: uazo/bromite-buildtools/images/build-deps@master
        with:
          version: ${{ env.VERSION }}
        
      - name: Check chromium image
        uses: uazo/bromite-buildtools/images/chr-source@master
        with:
          version: ${{ env.VERSION }}

      - name: Check bromite image
        uses: uazo/bromite-buildtools/images/bromite-source@master
        with:
          version: ${{ env.VERSION }}
          sha: ${{ github.sha }}
          
  build:
    runs-on: self-hosted
    needs: check_images
    if: success()

    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: xxx
        shell: bash
        run: echo "done"

#    container:
#      image: uazo/chromium:91.0.4472.146
#      options: "--privileged"
#      volumes:
#        - /storage/bromite/91.0.4472.146:/home/lg/working_dir/artifacs
